/**
 * Full-build helpers for the GitHub Copilot target.
 *
 * Each function produces one artifact's file content from a ResolvedArtifact.
 * These are used by both the full compile() path and the scaffold path (buildInstructionsFile,
 * buildSkillMd shared by scaffoldRule and scaffoldSkill respectively).
 */
import type { ResolvedArtifact, ResolvedCatalog } from '../../types';
import { renderBoundarySection } from '../shared/boundary';
import { renderArtifact } from '../emit';
import { applyLexicon } from '../lexicon';
import { COPILOT_LEXICON } from './lexicon';
import { COPILOT_SKILL_SPEC } from './spec/skill';
import { COPILOT_RULE_SPEC } from './spec/rule';
import { COPILOT_PROMPT_SPEC } from './spec/prompt';

/**
 * Builds .github/copilot-instructions.md from shared (cross-language) rules.
 *
 * No KindEmitSpec backs this aggregate (it has no per-artifact frontmatter to map), so its
 * citation is declared directly: see COPILOT_INSTRUCTIONS_DOC (../doc-refs.ts), tracked for
 * staleness via src/targets/all-emit-specs.ts's AGGREGATE_DOC_REFS. Same reasoning as
 * renderAgentSection above for the explicit `applyLexicon` call — this bypasses renderArtifact
 * entirely, so it needs its own lexicon pass.
 */
export function buildCopilotInstructions(sharedRules: ResolvedArtifact[]): string {
  const sections = sharedRules.map(rule => {
    const title = rule.frontmatter.title as string;
    const body = applyLexicon(rule.resolvedBody ?? rule.body, COPILOT_LEXICON);
    return `## ${title}\n\n${body}`;
  });

  return [
    '# Copilot Instructions',
    '',
    '<!-- Generated by sigil. Edit source in catalog/shared/rules/. -->',
    '<!-- These rules apply to every file in this repository. -->',
    '',
    ...sections,
    '',
  ].join('\n');
}

/**
 * Builds a .github/instructions/<slug>.instructions.md for a rule.
 * `applyTo` is derived from the authored `appliesTo` regardless of `language` — a
 * language-less shared rule keeps its own narrowed globs. Only a rule with no
 * `appliesTo` at all falls back to "**" (applies to every file). The applyTo
 * frontmatter field uses Copilot's comma-separated glob syntax.
 */
export function buildInstructionsFile(rule: ResolvedArtifact): string {
  return renderArtifact(COPILOT_RULE_SPEC, rule, {});
}

/**
 * Builds a .github/skills/<name>/SKILL.md for the native Agent Skills open standard.
 *
 * Frontmatter uses only `name` and `description` — NO `applyTo`/`paths`, because Copilot
 * skills load by description relevance rather than file-path matching.
 * Resolved rule bodies are inlined under "## Coding guidelines to apply" so the skill
 * stays self-contained even when installed with --no-deps.
 *
 * Delegates to the declarative spec in `spec/skill.ts` — see spec-types.ts for why the format
 * knowledge lives there rather than here.
 *
 * `catalog`/`installSet`, when provided, drive the same conditional `## Boundary` rendering
 * `renderAgentSection` below already does for a skill's own `relatedArtifacts`.
 */
export function buildSkillMd(
  skill: ResolvedArtifact,
  catalog?: ResolvedCatalog,
  installSet?: Set<string>,
): string {
  return renderArtifact(COPILOT_SKILL_SPEC, skill, { catalog, installSet });
}

/**
 * Builds a .github/prompts/<slug>.prompt.md for a catalog `prompt` or `workflow`.
 *
 * Copilot prompt files use YAML frontmatter (agent, description, tools) and are invoked
 * as /name in Copilot Chat. Note: "prompt file" is Copilot's native term — Claude Code
 * calls the equivalent artifact a "custom command" (no "prompt" artifact type there).
 *
 * `applyTo` is NOT valid inside .prompt.md — it belongs only in .instructions.md.
 * `agent:` is the current field name (renamed from `mode:` in recent Copilot docs).
 * `{{name}}` placeholders in the body are translated to `${input:name}` (VS Code input
 * variable syntax). The 2-part form is used deliberately — 3-part `${input:name:placeholder}`
 * breaks when the description contains a colon (e.g. "Options: reviewer, junior").
 * Delegates to the declarative spec in `spec/prompt.ts`.
 */
export function buildPromptFile(prompt: ResolvedArtifact): string {
  return renderArtifact(COPILOT_PROMPT_SPEC, prompt, {});
}

/**
 * Renders one agent's AGENTS.md section, including its Boundary block when co-present artifacts
 * exist. This is a hand-rolled aggregate (no KindEmitSpec — see buildAgentsMd's own doc comment),
 * so unlike `.github/agents/<name>.agent.md` (COPILOT_AGENT_SPEC, routed through renderArtifact)
 * it does NOT get the lexicon pass for free; `applyLexicon` is called directly here so a body
 * written once for both providers ({sigil:conventions-file}, …) still translates correctly in
 * this aggregate too — see docs/decisions/provider-neutral-body-lexicon-2026-08.md for the audit
 * that found this second, independent bypass of the same translation step.
 */
function renderAgentSection(
  agent: ResolvedArtifact,
  installSet: Set<string> | undefined,
  catalog: ResolvedCatalog | undefined,
): string {
  const name = agent.frontmatter.name as string;
  const title = agent.frontmatter.title as string;
  const description = agent.frontmatter.description as string;

  // Conditional Boundary section — only for co-present related artifacts
  const boundaryLines = renderBoundarySection(agent, installSet, catalog);
  const agentBody = applyLexicon(agent.resolvedBody ?? agent.body, COPILOT_LEXICON);
  const bodySection =
    boundaryLines.length > 0 ? [...boundaryLines, agentBody].join('\n') : agentBody;

  return [`## ${name}`, '', `**${title}**`, '', description, '', bodySection].join('\n');
}

/**
 * Builds .github/AGENTS.md — a single file listing all agents, as a repository INSTRUCTIONS
 * document (per the agents.md open standard): prose context for coding agents, resolved
 * nearest-in-tree. It is NOT how Copilot surfaces custom agent MODES — that's a distinct
 * mechanism, `.github/agents/*.agent.md` (spec/agent.ts, COPILOT_AGENT_SPEC), read independently.
 * The `## <name>` per-agent sectioning below is sigil's own layout choice; the open standard
 * itself specifies no structure beyond "a markdown file."
 *
 * GitHub supports AGENTS.md anywhere in the repo; VS Code documents subfolder placement as
 * experimental (root is the only unconditionally-supported location on both) — see
 * VSCODE_INSTRUCTIONS_DOC.covers. Emission stays at `.github/AGENTS.md` here regardless — moving
 * it to the repo root would change output and is tracked as a follow-up, not done in this pass.
 *
 * When `catalog` is provided, each agent's `relatedArtifacts` are rendered as
 * a Boundary section — since AGENTS.md is a full-build output, all agents in the
 * file are considered co-present, so all related artifacts in the same file
 * get rendered.
 *
 * No KindEmitSpec backs this aggregate — its citations are AGENTS_MD_STANDARD_DOC (the standard
 * itself), COPILOT_INSTRUCTIONS_DOC, and VSCODE_INSTRUCTIONS_DOC (../doc-refs.ts, each consumer's
 * doc for actually reading it), tracked for staleness via
 * src/targets/all-emit-specs.ts's AGGREGATE_DOC_REFS.
 */
export function buildAgentsMd(agents: ResolvedArtifact[], catalog?: ResolvedCatalog): string {
  // In the full build, all agents in the file are co-present.
  const installSet = catalog ? new Set(agents.map(a => a.id)) : undefined;
  const sections = agents.map(agent => renderAgentSection(agent, installSet, catalog));

  return (
    [
      '# AI Agents',
      '',
      '<!-- Generated by sigil. Edit source in catalog/*/agents/. -->',
      '<!-- Use these agents in GitHub Copilot Chat by invoking their @name. -->',
      '',
      ...sections,
    ]
      .join('\n')
      .trimEnd() + '\n'
  );
}
