/**
 * Full-build helpers for the GitHub Copilot target.
 *
 * Each function produces one artifact's file content from a ResolvedArtifact.
 * These are used by both the full compile() path and the scaffold path (buildInstructionsFile,
 * buildSkillMd shared by scaffoldRule and scaffoldSkill respectively).
 */
import type { ResolvedArtifact, ResolvedCatalog } from '../../types';
import { yamlScalar } from '../yaml-util';
import { toCopilotPlaceholders } from '../prompt-args';
import { renderBoundarySection } from '../shared/boundary';

/** Builds .github/copilot-instructions.md from shared (cross-language) rules. */
export function buildCopilotInstructions(sharedRules: ResolvedArtifact[]): string {
  const sections = sharedRules.map(rule => {
    const title = rule.frontmatter.title as string;
    return `## ${title}\n\n${rule.resolvedBody ?? rule.body}`;
  });

  return [
    '# Copilot Instructions',
    '',
    '<!-- Generated by sigil. Edit source in catalog/shared/rules/. -->',
    '<!-- These rules apply to every file in this repository. -->',
    '',
    ...sections,
    '',
  ].join('\n');
}

/**
 * Builds a .github/instructions/<slug>.instructions.md for a rule.
 * Shared rules (no language) get applyTo: "**" so they apply to every file.
 * The applyTo frontmatter field uses Copilot's comma-separated glob syntax.
 */
export function buildInstructionsFile(rule: ResolvedArtifact): string {
  const hasLanguage = Boolean(rule.frontmatter.language);
  const appliesTo = hasLanguage
    ? ((rule.frontmatter.appliesTo as string[] | undefined) ?? ['**/*'])
    : ['**'];
  const applyToValue = appliesTo.join(',');

  const frontmatter = ['---', `applyTo: "${applyToValue}"`, '---'].join('\n');

  const title = rule.frontmatter.title as string;
  const body = rule.resolvedBody ?? rule.body;
  const sourceComment = hasLanguage
    ? `<!-- Generated by sigil — source: catalog/${rule.id}.rule.md -->`
    : `<!-- Generated by sigil — source: catalog/shared/rules/. -->`;

  return [frontmatter, '', `# ${title}`, '', sourceComment, '', body, ''].join('\n');
}

/**
 * Builds a .github/skills/<name>/SKILL.md for the native Agent Skills open standard.
 *
 * Frontmatter uses only `name` and `description` — NO `applyTo`/`paths`, because Copilot
 * skills load by description relevance rather than file-path matching.
 * Resolved rule bodies are inlined under "## Coding guidelines to apply" so the skill
 * stays self-contained even when installed with --no-deps.
 */
export function buildSkillMd(skill: ResolvedArtifact): string {
  const name = skill.frontmatter.name as string;
  const description = skill.frontmatter.description as string;

  const frontmatter = [
    '---',
    `name: ${name}`,
    `description: ${yamlScalar(description)}`,
    '---',
  ].join('\n');

  const parts = [frontmatter, '', skill.body];

  const rules = skill.resolvedRules ?? [];
  if (rules.length > 0) {
    parts.push('', '---', '', '## Coding guidelines to apply', '');
    for (const rule of rules) {
      const ruleTitle = rule.frontmatter.title as string;
      parts.push(`### ${ruleTitle}`, '', rule.resolvedBody ?? rule.body, '');
    }
  }

  return parts.join('\n').trimEnd() + '\n';
}

/**
 * Builds a .github/prompts/<slug>.prompt.md for a catalog `prompt` or `workflow`.
 *
 * Copilot prompt files use YAML frontmatter (agent, description, tools) and are invoked
 * as /name in Copilot Chat. Note: "prompt file" is Copilot's native term — Claude Code
 * calls the equivalent artifact a "custom command" (no "prompt" artifact type there).
 *
 * `applyTo` is NOT valid inside .prompt.md — it belongs only in .instructions.md.
 * `agent:` is the current field name (renamed from `mode:` in recent Copilot docs).
 * `{{name}}` placeholders in the body are translated to `${input:name}` (VS Code input
 * variable syntax). The 2-part form is used deliberately — 3-part `${input:name:placeholder}`
 * breaks when the description contains a colon (e.g. "Options: reviewer, junior").
 */
export function buildPromptFile(prompt: ResolvedArtifact): string {
  const description = prompt.frontmatter.description as string;

  const frontmatterLines = [
    '---',
    'agent: agent',
    `description: ${yamlScalar(description)}`,
    'tools:',
    '  - codebase',
    '  - github',
    '---',
  ];

  const parts = [frontmatterLines.join('\n'), '', toCopilotPlaceholders(prompt.body)];

  return parts.join('\n').trimEnd() + '\n';
}

/**
 * Builds .github/AGENTS.md — a single file listing all agents.
 * Copilot reads this to surface custom agent modes.
 *
 * When `catalog` is provided, each agent's `relatedArtifacts` are rendered as
 * a Boundary section — since AGENTS.md is a full-build output, all agents in the
 * file are considered co-present, so all related artifacts in the same file
 * get rendered.
 */
export function buildAgentsMd(agents: ResolvedArtifact[], catalog?: ResolvedCatalog): string {
  // In the full build, all agents in the file are co-present.
  const installSet = catalog ? new Set(agents.map(a => a.id)) : undefined;

  const sections = agents.map(agent => {
    const name = agent.frontmatter.name as string;
    const title = agent.frontmatter.title as string;
    const description = agent.frontmatter.description as string;

    // Conditional Boundary section — only for co-present related artifacts
    const boundaryLines = renderBoundarySection(agent, installSet, catalog);

    const bodySection =
      boundaryLines.length > 0 ? [...boundaryLines, agent.body].join('\n') : agent.body;

    return [`## ${name}`, '', `**${title}**`, '', description, '', bodySection].join('\n');
  });

  return (
    [
      '# AI Agents',
      '',
      '<!-- Generated by sigil. Edit source in catalog/*/agents/. -->',
      '<!-- Use these agents in GitHub Copilot Chat by invoking their @name. -->',
      '',
      ...sections,
    ]
      .join('\n')
      .trimEnd() + '\n'
  );
}
