/**
 * Copilot `rule` emission spec — `.instructions.md`. `applyTo` is derived from the authored
 * `appliesTo` regardless of `language` — a language-less shared rule keeps its own narrowed
 * globs. Only a rule with no `appliesTo` at all falls back to "**" (applies to every file).
 * Copilot's `applyTo` frontmatter uses a comma-separated glob syntax, unlike Claude's `paths:`
 * YAML list.
 */
import type { KindEmitSpec, FieldMapping, BodySectionSpec } from '../../spec-types';
import { COPILOT_INSTRUCTIONS_DOC, VSCODE_INSTRUCTIONS_DOC } from '../../doc-refs';
import { COPILOT_LEXICON } from '../lexicon';
import { UNTRANSLATED_TOKEN_FORBID, CLAUDE_LITERAL_FORBIDS_ON_COPILOT } from '../../lexicon-forbid';

const applyToMapping: FieldMapping = {
  from: 'appliesTo',
  to: 'applyTo',
  required: true,
  alwaysEmit: true, // must always be present — falls back to "**" when appliesTo is unauthored
  serialize: v => {
    const authored = v as string[] | undefined;
    const appliesTo = authored && authored.length > 0 ? authored : ['**'];
    return `applyTo: "${appliesTo.join(',')}"`;
  },
};

const titleAndSourceSection: BodySectionSpec = {
  id: 'titleAndSource',
  position: 'before',
  render: artifact => {
    const hasLanguage = Boolean(artifact.frontmatter.language);
    const sourceComment = hasLanguage
      ? `<!-- Generated by sigil — source: catalog/${artifact.id}.rule.md -->`
      : `<!-- Generated by sigil — source: catalog/shared/rules/. -->`;
    return [`# ${artifact.frontmatter.title as string}`, '', sourceComment, ''];
  },
};

export const COPILOT_RULE_SPEC: KindEmitSpec = {
  kind: 'rule',
  outputPath: artifact => `.github/instructions/${artifact.id.replace(/\//g, '-')}.instructions.md`,
  pathPattern: /\.github\/instructions\/.*\.instructions\.md$/,
  frontmatter: [applyToMapping],
  emitEmptyFrontmatter: false,
  body: [titleAndSourceSection],
  forbiddenKeys: ['name', 'agent'],
  lexicon: COPILOT_LEXICON,
  bodyForbids: [UNTRANSLATED_TOKEN_FORBID, ...CLAUDE_LITERAL_FORBIDS_ON_COPILOT],
  // GitHub's own docs restrict path-specific instructions to cloud agent + code review on
  // github.com; VS Code applies .instructions.md generally — a real divergence, cite both.
  docs: [COPILOT_INSTRUCTIONS_DOC, VSCODE_INSTRUCTIONS_DOC],
};
