/**
 * Repo-wide rules and the aggregate instructions file they go into, shared by every target that
 * writes one (Copilot's `.github/copilot-instructions.md`, the open-standard `AGENTS.md`). A rule is
 * repo-wide when it has no language and applies to every file; folding a narrower rule into such a
 * file would silently widen it to the whole repository.
 *
 * @module
 */
import type { ResolvedArtifact } from '../../types';
import { applyLexicon, type ProviderLexicon } from '../lexicon';

const REPO_WIDE_GLOBS: ReadonlySet<string> = new Set(['**', '**/*']);

/** True for a language-less rule with no `appliesTo`, or one scoped only to every file. */
export function isRepoWideRule(rule: ResolvedArtifact): boolean {
  if (rule.frontmatter.language) return false;
  const globs = rule.frontmatter.appliesTo as string[] | undefined;
  return !globs || globs.every(glob => REPO_WIDE_GLOBS.has(glob));
}

/**
 * One instructions document from repo-wide rules: `heading`, then each rule as a `##` section. No
 * KindEmitSpec renders it, so it applies the target's lexicon itself.
 */
export function renderRulesDocument(
  heading: string,
  rules: readonly ResolvedArtifact[],
  lexicon: ProviderLexicon,
): string {
  const sections = rules.map(rule => {
    const title = rule.frontmatter.title as string;
    const body = applyLexicon(rule.resolvedBody ?? rule.body, lexicon);
    return `## ${title}\n\n${body}`;
  });
  return [
    heading,
    '',
    '<!-- Generated by sigil. Edit source in catalog/shared/rules/. -->',
    '<!-- These rules apply to every file in this repository. -->',
    '',
    ...sections,
    '',
  ].join('\n');
}
