/**
 * Renders docs/reference/capabilities.md — the kind × target table per channel — from the
 * registered targets' capability tables. Pure (no I/O): ./emit-capability-doc.ts writes it during
 * `npm run build`, and test/targets/capabilities.test.ts fails when the committed file is stale,
 * so the documentation can never drift from what the code actually does.
 *
 * @module
 */
import type { Target } from '../types';
import { ALL_KINDS } from '../kinds';
import { CHANNELS, type ChannelId, type KindSupport } from './capability-types';

const HEADER = [
  '<!-- GENERATED by `npm run build` from src/targets/<provider>/capabilities.ts — do not edit by hand. -->',
  '',
  '# Kind support per target and channel',
  '',
  'Which artifact kinds each target delivers on each channel. `scaffold` = files written into a',
  "project by `sigil add` (and the target's `sigil build` layout); `plugin` = marketplace plugins",
  'built by `sigil build`. `native` = emitted as its own file or config fragment; `via inline` =',
  'carried inside the skills that `uses:` it; `—` = not delivered (see the numbered note). Why the',
  'channels are split this way: [distribution-channels-2026-09](../decisions/distribution-channels-2026-09.md).',
];

type ViaSupport = Extract<KindSupport, { mode: 'via' }>;

/** What each `via` delivery means — keyed by `as`, so a new value fails to compile until described. */
const VIA_PROSE: Readonly<Record<ViaSupport['as'], string>> = {
  inline: 'folded into each skill that `uses:` it',
};

/** One cell's label, registering a numbered note for non-native rows. */
function cellLabel(support: KindSupport, note: (text: string) => number): string {
  if (support.mode === 'native') return 'native';
  if (support.mode === 'via') {
    const text = `${VIA_PROSE[support.as]} — ${docLinks(support.docs)}`;
    return `via ${support.as} (${note(text)})`;
  }
  return `— (${note(support.reason + docSuffix(support.docs))})`;
}

function docLinks(docs: readonly { title: string; url: string }[]): string {
  return docs.map(d => `[${d.title}](${d.url})`).join(', ');
}

function docSuffix(docs: readonly { title: string; url: string }[] | undefined): string {
  return docs && docs.length > 0 ? ` — ${docLinks(docs)}` : '';
}

/** Kind rows for one channel's table; non-native cells register their numbered notes. */
function tableRows(
  targets: readonly Target[],
  channel: ChannelId,
  note: (text: string) => number,
): string[] {
  return ALL_KINDS.map(kind => {
    const cells = targets.map(t => cellLabel(t.capabilities[channel]![kind], note));
    return `| ${kind} | ${cells.join(' | ')} |`;
  });
}

/** The table + notes for one channel, or no lines when no target has that channel. */
function channelSection(targets: readonly Target[], channel: ChannelId): string[] {
  const withChannel = targets.filter(t => t.capabilities[channel] !== undefined);
  if (withChannel.length === 0) return [];

  const notes: string[] = [];
  // Identical reasons share one numbered note instead of repeating it per cell.
  const note = (text: string): number => {
    const existing = notes.indexOf(text);
    return existing >= 0 ? existing + 1 : notes.push(text);
  };
  return [
    `## ${channel}`,
    '',
    `| Kind | ${withChannel.map(t => t.name).join(' | ')} |`,
    `| --- | ${withChannel.map(() => '---').join(' | ')} |`,
    ...tableRows(withChannel, channel, note),
    '',
    ...notes.map((text, i) => `${i + 1}. ${text}`),
  ];
}

/** Renders the full capabilities document for `targets` (in registration order). */
export function renderCapabilityMatrix(targets: readonly Target[]): string {
  const sections = CHANNELS.map(channel => channelSection(targets, channel)).filter(
    lines => lines.length > 0,
  );
  return [...HEADER, ...sections.flatMap(lines => ['', ...lines])].join('\n') + '\n';
}
