/**
 * Renders `catalog/README.md`: the catalog's anatomy for a person browsing the folders, generated
 * from the same data the checks read (`catalog/standard.yaml`, `KIND_REGISTRY` and the targets'
 * capability tables), so the page can't drift from what `sigil sync --check` enforces. Written by
 * `npm run build` (emit-catalog-readme.ts); test/catalog-readme.test.ts fails when it is stale.
 *
 * @module
 */
import { ALL_KINDS, KIND_REGISTRY } from './kinds';
import type { CatalogStandard, FamilyDef } from './catalog-standard';
import type { ArtifactKind } from './types';
import { getAllTargets } from './targets/index';
import { supportsKind } from './targets/capabilities';

/** Where one artifact of `kind` lives inside a namespace folder. */
function kindPath(kind: ArtifactKind): string {
  const d = KIND_REGISTRY[kind];
  return d.isDirectoryBacked
    ? `\`${d.sourceDir}/<name>/${d.sourceSuffix}\` (+ optional \`references/\`)`
    : `\`${d.sourceDir}/<name>${d.sourceSuffix}\``;
}

/** How a kind reaches a project, from the targets' capability tables. */
function delivery(kind: ArtifactKind): string {
  if (!getAllTargets().some(target => supportsKind(target, kind))) {
    return 'not delivered on its own (no target emits it)';
  }
  return KIND_REGISTRY[kind].isConfig ? 'merged into a JSON config' : 'whole file';
}

function kindsTable(): string[] {
  return [
    '| Kind | File | Delivered as |',
    '| --- | --- | --- |',
    ...ALL_KINDS.map(kind => `| ${kind} | ${kindPath(kind)} | ${delivery(kind)} |`),
  ];
}

/** The reference files a family's members carry, as `name (role)` plus the stack files. */
function referencesCell(family: FamilyDef): string {
  const refs = family.references;
  if (!refs) return '—';
  const files = Object.entries(refs.files).map(([name, role]) => `${name} (${role})`);
  const perMember = Object.entries(refs.members).map(
    ([id, own]) => `${id}: ${Object.keys(own).join(', ')}`,
  );
  const stacks = refs.stacks ? ['stack-<id> (one per stack)'] : [];
  return [...stacks, ...files, ...perMember].join('; ');
}

function familiesTable(standard: CatalogStandard): string[] {
  return [
    '| Family | Kind | Title | Members | Sections | References |',
    '| --- | --- | --- | --- | --- | --- |',
    ...standard.families.map(family => {
      const members = family.members.map(id => `\`${id}\``).join(', ');
      const sections = family.sections ? String(family.sections.length) : '—';
      const title = family.title ? `${family.title} (<language>)` : '—';
      const row = [family.id, family.kind, title, members, sections, referencesCell(family)];
      return `| ${row.join(' | ')} |`;
    }),
  ];
}

const INTRO = [
  '# Catalog',
  '',
  '<!-- Generated by `npm run build` from catalog/standard.yaml and src/kinds.ts. Do not edit. -->',
  '',
  'The source every target is built from. One standard holds for every artifact; this page is that',
  'standard, generated from the data `sigil sync --check` enforces',
  '([family-skeleton-standard-2026-10.md](../docs/decisions/family-skeleton-standard-2026-10.md),',
  '[catalog-layout-standard-2026-10.md](../docs/decisions/catalog-layout-standard-2026-10.md)).',
  '',
  '## Where an artifact goes',
  '',
  '- No language variation: `shared/`.',
  "- Varies with the project's language: `languages/<language>/`, prefixed with the language's",
  '  `prefix` (`ts-`, `py-`, ...). Each language names its prefix and stack in `language.yaml`.',
  "- Varies with a stack the task chooses: one neutral shared skill; each stack's text is a stack",
  '  part in the language that owns the stack (`languages/<home>/stack-parts/<skill>.md`), shipped',
  "  as the skill's `references/stack-<id>.md` and listed by a generated table",
  '  (`<!-- stack-index -->` in SKILL.md). `shared/` never holds language-specific text.',
  '',
  'Grouping for installs lives in `packs.yaml`, never in folders.',
  '',
  '## Files per kind',
  '',
];

const SKILL_ANATOMY = [
  '',
  '## Skill anatomy',
  '',
  'Every skill is a folder with a `SKILL.md`: the steps, always. Its family decides whether it also',
  'carries a flat `references/` folder, and which files, by role:',
  '',
  '- **core**: detail the steps read on demand, so `SKILL.md` stays short;',
  "- **brief**: the hand-off an agent reads (an auditor reads its skill's brief);",
  '- **examples**: worked examples;',
  '- **stack**: one `stack-<id>.md` per declared stack, all with one H2 skeleton, read one at a time.',
  '',
  'A family that declares no references is `SKILL.md` only, the official minimum of every tool. A',
  'skill carries references only when it outgrows one file or holds variants used one at a time.',
  'Every target ships reference files next to `SKILL.md` and translates them like the body.',
  '',
  '## Families',
  '',
  'Every agent, rule and skill belongs to exactly one family. Members share their H2 sections (in',
  "order), set exactly the family's frontmatter keys, take its title, carry its reference files",
  'and load rules and agents from the same families.',
  '',
];

/** The whole page for `standard`. */
export function renderCatalogReadme(standard: CatalogStandard): string {
  const stacks = standard.stacks
    .map(s => `\`${s.id}\` (${s.displayName}${s.home ? `, home \`${s.home}\`` : ''})`)
    .join(', ');
  return [
    ...INTRO,
    ...kindsTable(),
    ...SKILL_ANATOMY,
    ...familiesTable(standard),
    '',
    '## Stacks, severities and bases',
    '',
    `- Stacks: ${stacks}.`,
    `- Report severities, highest first: ${standard.severities.join(', ')}.`,
    `- Bases (shared rules other rules extend): ${standard.bases.map(b => `\`${b}\``).join(', ')}.`,
    '',
  ].join('\n');
}
